# Generated by Django 2.2 on 2019-06-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_designation', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=500)),
                ('cpd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.CPD')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.Frequency')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_designation', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_designation', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_designation', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_designation', models.CharField(max_length=500)),
                ('output_description', models.CharField(max_length=500, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.Section')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_value', models.FloatField()),
                ('value', models.FloatField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.Indicator')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='InvolvedPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.Indicator')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.Partner')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.Output'),
        ),
        migrations.CreateModel(
            name='ConcernedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.Indicator')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators_app.Report')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
